<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2006

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce 2006 Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:n1="vuln_report" xmlns="vuln_report" exclude-result-prefixes="xs n1">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/n1:ConsolidatedProjects">
		<Findings>
			<xsl:attribute name="xsi:schemaLocation">vuln_report C:/_ABN/ORG-OW~1/V-Drive/APPLIC~1/v0.83/VulnReport_Files/xsd/GVADataFeedXsd_v0.5.xsd</xsl:attribute>
			<Finding>
				<xsl:for-each select="n1:Project">
					<xsl:for-each select="n1:Targets">
						<xsl:for-each select="n1:Target">
							<xsl:for-each select="n1:Findings">
								<xsl:for-each select="n1:Finding">
									<xsl:for-each select="@Layer">
										<xsl:attribute name="Layer">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n1:Project">
					<xsl:for-each select="n1:Targets">
						<xsl:for-each select="n1:Target">
							<xsl:for-each select="n1:Findings">
								<xsl:for-each select="n1:Finding">
									<xsl:for-each select="@Category">
										<xsl:attribute name="Category">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n1:Project">
					<xsl:for-each select="n1:Targets">
						<xsl:for-each select="n1:Target">
							<xsl:for-each select="n1:Findings">
								<xsl:for-each select="n1:Finding">
									<xsl:for-each select="@Vulnerability">
										<xsl:attribute name="Vulnerability">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n1:Project">
					<xsl:for-each select="n1:Targets">
						<xsl:for-each select="n1:Target">
							<xsl:for-each select="n1:Findings">
								<xsl:for-each select="n1:Finding">
									<xsl:for-each select="@IncludeInReport">
										<xsl:attribute name="IncludeInReport">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n1:Project">
					<xsl:for-each select="n1:Targets">
						<xsl:for-each select="n1:Target">
							<xsl:for-each select="n1:Findings">
								<xsl:for-each select="n1:Finding">
									<xsl:for-each select="@Impact">
										<xsl:attribute name="Impact">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n1:Project">
					<xsl:for-each select="n1:Targets">
						<xsl:for-each select="n1:Target">
							<xsl:for-each select="n1:Findings">
								<xsl:for-each select="n1:Finding">
									<xsl:for-each select="@Probability">
										<xsl:attribute name="Probability">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n1:Project">
					<xsl:for-each select="n1:Targets">
						<xsl:for-each select="n1:Target">
							<xsl:for-each select="n1:Findings">
								<xsl:for-each select="n1:Finding">
									<xsl:for-each select="@Issue-id">
										<xsl:attribute name="Issue-id">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="n1:Project">
					<xsl:for-each select="n1:Targets">
						<xsl:for-each select="n1:Target">
							<xsl:for-each select="n1:Findings">
								<xsl:for-each select="n1:Finding">
									<xsl:for-each select="@Owner">
										<xsl:attribute name="Owner">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
				<Metadata>
					<xsl:for-each select="n1:Project">
						<xsl:for-each select="n1:Metadata">
							<xsl:for-each select="n1:project_number">
								<project_number>
									<xsl:value-of select="."/>
								</project_number>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="n1:Project">
						<xsl:for-each select="n1:Metadata">
							<xsl:for-each select="n1:project_name">
								<project_name>
									<xsl:value-of select="."/>
								</project_name>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</Metadata>
				<Target>
					<xsl:for-each select="n1:Project">
						<xsl:for-each select="n1:Targets">
							<xsl:for-each select="n1:Target">
								<xsl:for-each select="@name">
									<xsl:attribute name="name">
										<xsl:value-of select="."/>
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="n1:Project">
						<xsl:for-each select="n1:Targets">
							<xsl:for-each select="n1:Target">
								<xsl:for-each select="@type">
									<xsl:attribute name="type">
										<xsl:value-of select="."/>
									</xsl:attribute>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</Target>
			</Finding>
		</Findings>
	</xsl:template>
</xsl:stylesheet>
