//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace HacmeBank_v2_Website.WS_UsersCommunity {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_UsersCommunitySoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public class WS_UsersCommunity : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
		public WS_UsersCommunity(string ipAddressOfWebService ) 
		{
			this.Url = "http://" + ipAddressOfWebService + "/HacmeBank_v2_WS/WebServices/UsersCommunity.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PostMessage(string sessionID, string userID, string messageSubject, string messageText) {
            this.Invoke("PostMessage", new object[] {
                        sessionID,
                        userID,
                        messageSubject,
                        messageText});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPostMessage(string sessionID, string userID, string messageSubject, string messageText, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PostMessage", new object[] {
                        sessionID,
                        userID,
                        messageSubject,
                        messageText}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPostMessage(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPostedMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetPostedMessages(string sessionID) {
            object[] results = this.Invoke("GetPostedMessages", new object[] {
                        sessionID});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPostedMessages(string sessionID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPostedMessages", new object[] {
                        sessionID}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGetPostedMessages(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteMessage(string sessionID, string messageID) {
            object[] results = this.Invoke("DeleteMessage", new object[] {
                        sessionID,
                        messageID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteMessage(string sessionID, string messageID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteMessage", new object[] {
                        sessionID,
                        messageID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndDeleteMessage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
}
